### ISSUE TITLE
Ledger utility to identify transactions associated with in doubt state

### ISSUE THREAD

**Issue by denyeart** [hyperledger/fabric#2788]
GOAL
Identify transactions that have caused divergent state.

INPUT
Set of keys in question (JSON output from state comparison utility)

APPROACH
Traverse the block store on each peer (separately) to identify and extract transactions that wrote mismatched keys

OUTPUT
Set of transactions that wrote the keys (in human readable format)
All tx validation codes from the respective blocks
Block commit hashes from the respective blocks (available on channels created in v1.4.2 and later)

**Comment by jcastrence** [comment]
In bold are assumptions and questions on the implementation of the tool

GOAL 
Identify potentially divergent transactions

INPUT 
Set of keys in question (from file utility or otherwise)

**Format: json file holding one diffRecord list. Only the JSON elements "namespace" and key" will be parsed. Therefore it will also be possible to hand craft a JSON array of "namespace" and "key" pairs that the utility will use as input.**

APPROACH 
Traverse the block store on each peer (separately) to identify and extract transactions that wrote mismatched keys

**Block store: list of blocks for peer, can be accessed from peer file system (no db access required)
Block: list of transactions and metadata on a block
Functions / files relevant to accessing the block store?
Found so far: blkstorage package, blockstore_provider.go (BlockStoreProvider type), leveldbhelper.Provider, fileledger package, fileledger/factory.go
What is meant by separately? It means that the utility would be run against peer1's block store, and then peer2's block store, so that the user can inspect and compare the outputs. The assumption is that you can only access one peer's file system at a time.
Does this mean the tool is ran twice, once for each peer? Or that the tool is ran once and checks both peers sequentially?
Functions / files relevant to transaction structure?
How are txs ordered?**

OUTPUT 
Set of transactions that wrote the keys (in human readable format) All tx validation codes from the respective blocks Block commit hashes from the respective blocks (available on channels created in v1.4.2 and later)

**File types for the different outputs?
JSON, log back to user, or both like compare utility? In success case, output to JSON. In error case, log back to user.
All output in the same file or different file for each (txs, tx codes, hashes)? I think we could output to a single file, with JSON in the following structure:
namespace
..key
....transaction id
......transaction number (in block)
......transaction validation status
......transaction content (in JSON form, not sure if we have a preferred JSON tx structure already?)
......block number
......block commit hash
e.g. a namespace/key may have been updated in N different txids, and they can all be seen in the JSON file, along with their respective block number and block commit hash (if two transactions appear in the same block that is ok, we'd simply include the same block number and commit hash in both tx entries). I think we could skip the "All tx validation codes from the respective block".**


**Main Algorithm Basic Pseudocode**

**Read json from input file, get diffRecord list
For a single peer:
Traverse blocks
Traverse transactions
If transaction contains namespace and key of a diffRecord, write transaction to json output and tx validation code to json output
If write occurred, write block commit hash to json output
Write all outputs
Question - do we care about transactions that have the key as readset only? Or only transactions that have the key in writeset?**

**Comment by manish-sethi** [comment]
The above comment does not appear very readable but whatever I could interpret, listing below a few additional points.
- If not supplied the key list from the user, limit the initial input to top-k divergent keys.
- For commit hash dump, we can simply dump the first commit hash divergence and full corresponding block as a separate JSON in the file, instead of printing with each entry as this may happen that the first commit hash diverged before the earliest divergence of the key in the snapshots.
- For a particular key, stop fetching further data when the block number exceeds the max(of versions) present in the `diffRecord`

To answer the questions posed:
- If the key being tracked appears only in the read-set in the transaction, this can be ignored
- If we process one peer at a time, we can keep the intermediate output in a KV store and after having scanned multiple peers, finally dump the combined output into JSON
