### ISSUE TITLE
Underlying errors do not get returned by gateway

### ISSUE THREAD

**Issue by denyeart** [hyperledger/fabric#2806]
When a gateway call to a peer function returns an error, the error does not get returned to the gateway client, only a generic gateway error message gets returned to client. Clients will therefore not know the cause of the error or how to fix.

For example, my error was that I was calling the wrong chaincode function, but the application client only received the generic error:
"Error: 10 ABORTED: failed to endorse transaction"
It did not receive the underlying error message from the endorser, which after adding debug code I can see is "error 500, Function put not found in contract SmartContract".

The reason is that rpcError() is used for gateway error handling, the error details that are passed in and set in status.WithDetails() do not get returned in the ultimate status.Err() error message, see line at:
https://github.com/hyperledger/fabric/blob/main/internal/pkg/gateway/apiutils.go#L77

**Comment by manish-sethi** [comment]
`status.Err()` returns a [custom error](https://github.com/grpc/grpc-go/blob/574137db7de3c10e010d5023626169f13540cef1/internal/status/status.go#L145) that includes the whole status object. In fact, as per [grpc code doc](https://github.com/grpc/grpc-go/blob/574137db7de3c10e010d5023626169f13540cef1/call.go#L28), all errors returned from grpc layer are of this type. So, in this design, the client would be expected to extract the details explicitly. For instance, a golang client would need to call [`status.Convert()`](https://github.com/grpc/grpc-go/blob/574137db7de3c10e010d5023626169f13540cef1/status/status.go#L95) and then access the [`Details()`](https://github.com/grpc/grpc-go/blob/39df0b324aeb322f4e73ce4f27741dec2aa069cb/status/status.go#L154). Yes, simply calling `Error()` in the golang client [omits the details](https://github.com/grpc/grpc-go/blob/574137db7de3c10e010d5023626169f13540cef1/internal/status/status.go#L140).

Further details of this error model can be found [here](https://cloud.google.com/apis/design/errors).

I haven't tried these on any client side myself but if it works as expected, we can leave this as is.

**Comment by denyeart** [comment]
Ok, I see that status.Convert() does indeed convert the error back into a status object with the details containing the underlying errors. So this information must be getting returned to the grpc client, which in our case are the new slim SDKs. It looks like the new slim SDKs are only returning the generic error message back to the client applications, not the details containing the underlying error messages. I think the SDKs will need to be extended to pass the detailed errors back to the client applications. Errors are impossible to troubleshoot in the client application without the underlying error messages.

**Comment by bestbeforetoday** [comment]
I've opened hyperledger/fabric-gateway#158 to ensure we pass back gRPC errors directly to the client application so they can be converted to gRPC status and interrogated.

I think it would also be worth modifying the Gateway code within the peer to include appropriate detail text in the top-level error message to make the errors received by the client application more helpful even without converting them to gRPC status to interrogate the associated detail messages. For example, on a transaction function error response, instead of simply returning `"transaction evaluation error"` as the error message, we could return `fmt.Sprintf("evaluate error: %s", err.Error())` (where `err.Error()` contains the response status and message returned by the transaction function in the event of an error response).
