### ISSUE TITLE
In Fabric 2.2.3, when approve chaincode with different packege id, commit still can be success

### ISSUE THREAD

**Issue by heyouxian** [hyperledger/fabric#2932]
I found when different organization approve chaincode by "peer lifecycle chaincode approveformyorg", the "--collections-config" file content and the "--signature-policy" string must be strict equals to the one in "peer lifecycle chaincode commit".
But why there is no "--package-id" in commit command? If two organization install and approve different chaincode with same version, sequence, collection-config and signature-policy, then they can run different chaincode if endorse policy is 1 of n?

**Comment by kopaygorodsky** [comment]
If I'm not mistaken, packageId should be unique only in a context of an organization. It's ok to have different IDs of the same chaincode in different organizations. When you approve, you agree that at the specified sequence you trust your installed chaincode. 

From Fabric doc: 

`
The chaincode definition also includes the Package Identifier. This is a required parameter for each organization that wants to use the chaincode. The package ID does not need to be the same for all organizations. An organization can approve a chaincode definition without installing a chaincode package or including the identifier in the definition.
`

**Comment by heyouxian** [comment]
But in my testing, the package id is generated with format `<chaincode name>_<chaincode version>:<chaincode hash>`, I'm not sure how the `<chaincode hash>` is calculated, but I found the same java chaincode jar generated the same value in all organizations. So from my understanding, for different organizations on a channel, they should install the same chaincode with same name and version, and approved with same sequence. And commited command can check package id to make sure they use the same chaincode.

**Comment by denyeart** [comment]
The chaincode logic and resulting package id are not required to be the same at each org, and is not checked upon commit. This is because different organizations may add additional validation checks in the chaincode before endorsing. What is important is that each organization's chaincode execution results are the same, and this is checked for each transaction per the endorsement policy.

More details at https://hyperledger-fabric.readthedocs.io/en/latest/chaincode_lifecycle.html#organizations-install-different-chaincode-packages

This is working as designed, closing.
