### ISSUE TITLE
Documentation: Index issues

### ISSUE THREAD

**Issue by WaleedMortaja** [hyperledger/fabric#3351]
Hello,
I think there are some issues with the documentation index.

First, [Release Notes](https://hyperledger-fabric.readthedocs.io/en/release-2.2/whatsnew.html#release-notes) are visible in the index, even though it is a **section** of the [What's new in Hyperledger Fabric v2.x](https://hyperledger-fabric.readthedocs.io/en/release-2.2/whatsnew.html) **chapter**.

![image](https://user-images.githubusercontent.com/27075022/164721679-6ae03635-d4a9-42f4-8aa0-f4e133ad5c20.png)

Second, Some page(s) do not appear in the index. I found [this ledger page](https://hyperledger-fabric.readthedocs.io/en/release-2.2/ledger.html).

Are these intentional decisions or do they need to be fixed?

**Comment by denyeart** [comment]
Release notes section of What's New is intended to show in the table of contents so that people can find it easily.

The Ledger topic referenced has been replaced with:
https://hyperledger-fabric.readthedocs.io/en/latest/ledger/ledger.html

I've opened https://github.com/hyperledger/fabric/pull/3370 to remove the old ledger topic.
