### ISSUE TITLE
Go chaincode - CVE-2022-27664 (High) vulnerability - Go 1.18.6

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/fabric#3654]
Reported in hyperledger/fabric-contract-api-go#75

A chaincode container Go version of 1.18.6 or later should resolve this vulnerability

**Comment by davidkel** [comment]
As it's in an `x` package won't it be down to the version stored in the vendor package (and defined in the go.mod file) that the chaincode bundles rather than the version of the compiler that's used by ccenv ?

Although as an aside it would be good to move fabric to the latest 1.18 release anyway

**Comment by bviswana101** [comment]
I upgraded my dev environment to go 1.19.2 and update go.mod to set the minimum version as 1.19. After running `go mod tidy`, the version of  golang.org/x/net vendored is still the same (ie., v0.0.0-20220708220712-1185a9018129)

The latest versions of the package is https://pkg.go.dev/golang.org/x/net@v0.0.0-20221004154528-8021a29435af

**Comment by davidkel** [comment]
@bviswana101 
I don't believe this is related to the version of golang being used but rather the information stored in various go.mod files in the dependency tree, which results in that version of golang.org/x/net being defined as an indirect for a contract api chaincode. In fact if you look at fabric-chaincode-go, it's go.mod file declares this version as indirect, it may be necessary to drill down further to find the true direct dependency to determine if it's possible to address this. 

However there are 2 things that can be noted. First just because you import a package with a CVE against it doesn't mean you are susceptible to the vulnerability. Golang have released a vulnerability scanner described here https://go.dev/blog/vuln and when I run this tool against a simple contract api chaincode, I get this result

```
dave@DESKTOP-LLPUQ1H:~/test$ ~/go/bin/govulncheck ./...
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Scanning for dependencies with known vulnerabilities...
No vulnerabilities found.

=== Informational ===

The vulnerabilities below are in packages that you import, but your code
doesn't appear to call any vulnerable functions. You may not need to take any
action. See https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
for details.

Vulnerability #1: GO-2022-0969
  HTTP/2 server connections can hang forever waiting for a clean shutdown
  that was preempted by a fatal error. This condition can be exploited
  by a malicious client to cause a denial of service.

  Found in: golang.org/x/net/http2@v0.0.0-20220708220712-1185a9018129
  Fixed in: golang.org/x/net/http2@v0.0.0-20220906165146-f3363e06e74c
  More info: https://pkg.go.dev/vuln/GO-2022-0969
```

this tells me that it didn't detect any use of the vulnerability in my chaincode implementation

The other thing that can be done is to explicity replace the version of golang.org/x/net in your chaincode go.mod file, eg 

```
replace golang.org/x/net => golang.org/x/net v0.0.0-20221004154528-8021a29435af
```

re-vendor with `go mod vendor` 

and when I run the vulnerability scanner again I get

```
dave@DESKTOP-LLPUQ1H:~/test$ ~/go/bin/govulncheck ./...
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Scanning for dependencies with known vulnerabilities...
No vulnerabilities found.
```

The conclusion is that it's likely that  Go chaincode is not susceptible to this vulnerability (but check with the vulnerability tool yourself) and if there are concerns then you can use the replace directive to select a newer version

It is probably still worth trying to determine where the direct dependency for this version of the library is coming from

**Comment by denyeart** [comment]
Fabric is at Go 1.21 now, closing.
