### ISSUE TITLE
golang chaincode package and install error

### ISSUE THREAD

**Issue by phial3** [hyperledger/fabric#4102]
1. mycc chaincode project is go modules, `peer chaincode package mycc.out -n mycc -p mycc -v 1` command generate a `mycc.out` file

2. install package error message:
```
Error: install failed with status: 500 - chaincode installed to peer but could not build chaincode: docker build failed: docker image build failed: docker build failed: Error returned from build: 1 "go: cannot use modules with build cache disabled
```

```
Error: Bad response: 500 - chaincode installed to peer but could not build chaincode: docker build failed: docker image build failed: docker build failed: Error returned from build: 1 "go: cannot use modules with build cache disabled"
```

what's wrong is it?

**Comment by denyeart** [comment]
I'm not sure why go cache would be disabled in your environment. See some related discussion at https://github.com/golang/go/issues/29850.
Probably better to ask in the community forums since this looks environment specific rather than related to core Fabric code.
For getting community help, see
https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#communications-and-getting-help
