### ISSUE TITLE
A problem when update the contract.

### ISSUE THREAD

**Issue by csb123452010** [hyperledger/fabric#4315]
### Description

The first image shows the deployment of the go-version basic chaincode in testnetwork. You can see that the command is "chain code peer. add..," and the query is correct. 
The second image shows the deployment of the Java-version basic chaincode after the contract upgrade, and you can see that the command is "/root/chaincode jav...". 
At this point, there will be problems when querying all assets, as seen in image 3.  
But the data is still in the database, as seen in image 4.
On the other hand, I tried java version update to go version, and that is OK.
I'm not sure what's wrong with that.
 
![合约升级1](https://github.com/hyperledger/fabric/assets/97946841/b5d6fcaf-2a42-43fc-b1f1-48e2d6792b48)
![合约升级2](https://github.com/hyperledger/fabric/assets/97946841/63c52122-5724-4a56-9053-4d21a6cf1584)
![合约升级3](https://github.com/hyperledger/fabric/assets/97946841/8c288760-a8c6-40bd-b340-3a6bbba45ad1)
![合约升级4](https://github.com/hyperledger/fabric/assets/97946841/473348c2-00e8-4384-b1ff-a8f42d070b4e)

### Steps to reproduce

Follow https://hyperledger-fabric.readthedocs.io/en/latest/deploy_chaincode.html#

./network.sh up createChannel -s couchdb
./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-go -ccl go

then init the ledger, and update contract:

cd ../asset-transfer-basic/chaincode-java
./gradlew installDist
cd ../../test-network
......

**Comment by satota2** [comment]
@csb123452010 
This is probably because go-version chaincode and Java-version chaincode use different key names in Asset's JSON format.
- go-version uses [keys starting with an uppercase](https://github.com/hyperledger/fabric-samples/blob/9ee0aac2ae3ac57e27c3210751922b735b0ea556/asset-transfer-basic/chaincode-go/chaincode/smartcontract.go#L18C20-L18C20)
- java-version uses [keys starting with a lowercase](https://github.com/hyperledger/fabric-samples/blob/9ee0aac2ae3ac57e27c3210751922b735b0ea556/asset-transfer-basic/chaincode-java/src/main/java/org/hyperledger/fabric/samples/assettransfer/Asset.java#L52C5-L52C5)

Rather than a bug, it seems that the keys of the assets created by the respective versions of the chaincode are incompatible, so an asset with an empty value is returned.

**Comment by denyeart** [comment]
@csb123452010 I'll close since this is not a core fabric issue.
Go ahead and open an issue or PR against fabric-samples to make the samples consistent.

**Comment by csb123452010** [comment]
@satota2 Thank you for your answer!
