### ISSUE TITLE
How to use 'qscc/GetBlockByHash' in peer CLI and Java gateway?

### ISSUE THREAD

**Issue by 1164926307** [hyperledger/fabric#4994]
I failed to use qscc/GetBlockByHash on the Java gateway and peer CLI, and I couldn't find any relevant information on the network. But I can use 'blockchain explorer' to retrieve the correct information.
![{A4ZO2HHSLAH62I failed to use qscc/GetBlockByHash on the Java gateway and peer CLI, and I couldn't find any relevant information on the network. But I can use 'blockchain explorer' to retrieve the correct information.
{KB7V~R](https://github.com/user-attachments/assets/7e182f6a-e635-4271-b17a-ebe675aba53c)
![H%7TNSORU7JV@V{S9YLQM9V](https://github.com/user-attachments/assets/ecb057f7-0dd7-42fe-b16f-05dc12139799)
![KS@_64QU38IDXP}C65T9 LQ](https://github.com/user-attachments/assets/33e1416b-df8e-408d-8ba2-d1a2845181da)

**Comment by Rezacb0413** [comment]
> I failed to use qscc/GetBlockByHash on the Java gateway and peer CLI, and I couldn't find any relevant information on the network. But I can use 'blockchain explorer' to retrieve the correct information.
> ![{A4ZO2HHSLAH62I failed to use qscc/GetBlockByHash on the Java gateway and peer CLI, and I couldn't find any relevant information on the network. But I can use 'blockchain explorer' to retrieve the correct information.
> {KB7V~R](https://github.com/user-attachments/assets/7e182f6a-e635-4271-b17a-ebe675aba53c)
> ![H%7TNSORU7JV@V{S9YLQM9V](https://github.com/user-attachments/assets/ecb057f7-0dd7-42fe-b16f-05dc12139799)
> ![KS@_64QU38IDXP}C65T9 LQ](https://github.com/user-attachments/assets/33e1416b-df8e-408d-8ba2-d1a2845181da)
>

**Comment by samuelvenzi** [comment]
Hi, you cannot send the hash `string` directly. You need to decode it into bytes representing the hexadecimal, cast it to `string` and send it. Something like this:

```java
String blockHash = "your_hex_string_here";  // Replace with your actual hex string
byte[] hashBytes = HexFormat.of().parseHex(blockHash);
```

Let me know whether you are able to get the block by hash that way. I am interested in this because I am running into problems with the same function, as outlined in #5003.

**Comment by 1164926307** [comment]
@samuelvenzi  Thank you for your answer. I want to use hash to obtain blocks, but this query is not supported in Java gateway。
I see that there are only evaluateTransaction (String name, String... args) and evaluateTransaction (String name, byte[]... args) in the gateway args)

![ca9b9a216213ff5db351954839b91f0](https://github.com/user-attachments/assets/45c2df82-ced7-4b2f-8c98-66af3ef63469)

**Comment by bestbeforetoday** [comment]
To use mixed String and byte[] arguments in the Java client API, you might want to use `newProposal` instead of `evaluateTransaction`. For example:

```java
var result = contract.newProposal(transactionName)
        .addArguments(stringArg)
        .addArguments(bytesArg)
        .build()
        .evaluate();
```

The `addArguments` method has overloads that accept either String or byte[] arguments. You can call this multiple times and arguments are added in the order you make the calls. See the [Contract](https://hyperledger.github.io/fabric-gateway/main/api/java/org/hyperledger/fabric/client/Contract.html) API documentation for details and an example usage at the top of the page.

In reality, all String arguments are converted into byte[] by the client when transmitted to Fabric, so you could do this translation yourself and use the byte[] overload of `evaluateTransaction`. For example:

```java
var result = contract.evaluateTransaction(transactionName, stringArg.getBytes(StandardCharsets.UTF_8), bytesArg);
```

**Comment by 1164926307** [comment]
@bestbeforetoday    Thank you for your answer. I have tried this method before, but it may have been a coding error，It was the right thing to do and solved my problem

**Comment by bestbeforetoday** [comment]
Good to hear you have it working now. I’ll close the issue.
